apiVersion: v1
kind: ConfigMap
metadata:
  name: argocdccm
  namespace: test
data:
  index.html: |
    <html>
      <head>
     <meta http-equiv="refresh" content="5">
      </head>
      <head><title>Benvenuto Pagina Nginx Deployata in CD Argocd</title></head>
       <body>
        <h1>Servito da ConfigMap PUSHED BY ARGOCD V5.1.5.23 ore 20.06</h1>
      </body>
      
    </html>
