apiVersion: v1
kind: ConfigMap
metadata:
  name: argocdccm
  namespace: test
data:
  index.html: |
    <html>
      <head><title>Benvenuto Pagina Nginx Deployata in CD Argocd</title></head>
      <body>
        <h1>Servito da ConfigMap PUSHED BY ARGOCD V5.1.5.23 ore 19:56</h1>
      </body>
    </html>
