apiVersion: v1
kind: ConfigMap
metadata:
  name: argocdccm
  namespace: test
data:
  index.html: |
    <html>
      <head><title>Benvenuto Pagina Nginx</title></head>
      <body>
        <h1>Servito da ConfigMap V4.1.3 ore 11:30</h1>
      </body>
    </html>
