apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head><title>Benvenuto</title></head>
      <body><h1>Ciao da OpenShift!</h1></body>
    </html>
